version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null
  app:
    container_name: api
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - mongo
    volumes:
      - .:/app
