version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27011:27017
    restart: always
  app:
    container_name: api
    build: .
    ports:
      - 9090:9090
    depends_on:
      - mongo
